---
sudo: required
dist: focal

notifications:
  slack:
    on_failure: always

fleet_script_osquery_win_tasks : &fleet_script_osquery_win_tasks
      script:
          - echo "============================================="
          - echo "=============Installing Osquery=============="
          - choco install osquery --params='/InstallService' #This creates a new windows service that will auto-start the daemon.
          # - Start-Service osqueryd
          - echo "============================================="

fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version

fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -r requirements.txt


matrix:
  fast_finish: true
  include:

    - name: "deploy osquery Python 3.8.1 on Windows"
      os: windows
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.1
        - pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
        - python --version
        - pip install -r requirements.txt
      # <<: *fleet_install_tasks
      # <<: *fleet_script_tasks
      # <<: *fleet_script_osquery_win_tasks
      script:
          - echo "============================================="
          - echo "=============Installing Osquery=============="
          - choco install osquery --params='/InstallService' #This creates a new windows service that will auto-start the daemon.
          # - Start-Service osqueryd
          - echo "============================================="      
      after_success:
        - deactivate

    - name: "deploy osquery Python 3.8 on Windows"
      os: windows
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.1
        - pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      <<: *fleet_script_osquery_win_tasks
      after_success:
        - deactivate

    - name: "deploy osquery Python 3.7 on Windows"
      os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python --version 3.7.3
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      <<: *fleet_script_osquery_win_tasks
      after_success:
        - deactivate
