---
sudo: required

env:
  global:
  - VAGRANT_VERSION="2.2.9"
notifications:
  slack:
    on_failure: always

fleet_script_osquery_win_tasks : &fleet_script_osquery_win_tasks
      script:
          - echo "============================================="
          - echo "=============Installing Osquery=============="
          - choco install osquery --params='/InstallService' #This creates a new windows service that will auto-start the daemon.
          # - Start-Service osqueryd
          - echo "============================================="

fleet_script_osquery_macos_tasks : &fleet_script_osquery_macos_tasks
      script:
          - echo "============================================="
          - echo "=============Installing Osquery=============="
          - brew update
          - brew install osquery
          # - /usr/local/bin/osqueryi
          - echo "=============Post installation steps==============" #https://osquery.readthedocs.io/en/stable/installation/install-macos/
          - sudo ls -lai /var
          # - sudo ln -s /var/osquery /usr/local/share/osquery
          # - sudo mkdir /var/log/osquery
          - sudo ls -lai /usr/local/Cellar/osquery
          # - sudo chown root /usr/local/Cellar/osquery/1.7.3/bin/osqueryd
          # - sudo cp /var/osquery/osquery.example.conf /var/osquery/osquery.conf
          - echo "============================================="
        
fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version
fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -r requirements.txt


matrix:
  fast_finish: true
  include:

    - name: "deploy osquery w homebrew on macOS 10.15.5 osx xcode12u"
      os: osx
      osx_image: 
        - xcode12u
      addons:
        homebrew:
          packages:
          - osquery 
          update: true
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
        - sudo osqueryctl start
      after_success:
        - deactivate

    - name: "Python 2.7.17 on macOS xcode10.2"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      <<: *fleet_script_osquery_macos_tasks
      after_success:
        - deactivate

    - name: "Python 3.7.5 on macOS xcode10.2"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      <<: *fleet_script_osquery_macos_tasks
      after_success:
        - deactivate

    - name: "Python 3.7.5 on macOS xcode9.4 "
      os: osx
      osx_image: xcode9.4
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      <<: *fleet_script_osquery_macos_tasks
      after_success:
        - deactivate